### ISSUE TITLE
getkaiwa.com uses an invalid security certificate, SSL_ERROR_BAD_CERT_DOMAIN

### ISSUE THREAD

**Issue by grahamperrin** [digicoop/otalk#109]
Firefox reports: 

> …
> getkaiwa.com uses an invalid security certificate. 
> 
> The certificate is only valid for the following names: *.github.com, github.com, *.github.io, github.io 
> 
> Error code: SSL_ERROR_BAD_CERT_DOMAIN
> 
> …
> 
> Unable to communicate securely with peer: requested domain name does not match the server’s certificate. 
> …

**Comment by Nyco** [comment]
The GitHub homeage states: "[UNMAINTAINED] A modern XMPP Web client http://getkaiwa.com"

**Comment by grahamperrin** [comment]
Ah, thanks! 

I had followed an external reference to the https URL then in the absence of an UNMAINTAINED notice at the home page, I had gone straight for issues (overlooking the notice in GitHub).
